[Feat] 호텔 상세 페이지 추가
SOPT-all/35-COLLABORATION-WEB-AGODA pull request #26
Opened 2024-11-25 06:34 UTC by Leeyoonji23

## 📌 이슈 번호

- close # 19

## ✅ 구현 사항

1. HeaderSelection
![image](https://github.com/user-attachments/assets/e6aac353-e99d-418f-898b-096fffff2a1c)

2. Detail
![image](https://github.com/user-attachments/assets/1f140081-0995-464e-8ca9-e9bbc298c2a7)

3. 숙소 하이라이트 (Highlights.tsx)
![image](https://github.com/user-attachments/assets/c23aeee1-3e7a-4e0d-8159-e81a26a6f86f)

4. RateReview.tsx
![image](https://github.com/user-attachments/assets/61abeaa0-7110-412a-bcaf-350f8d31d96e)

5. TextReview.tsx

![image](https://github.com/user-attachments/assets/bcb4524c-5946-426a-8df3-3f9437640f4a)

-내용이 많으면 2줄만 보이게
-가로스크롤 가능

6. 위치평가 (Location.tsx)
![image](https://github.com/user-attachments/assets/7e7085f8-42f0-42ef-9f1c-ce4505b7abb8)

## 🔍 Review Point

-theme 을 사용해서 폰트나 색상 지정하는 건 알겠는데... font-weight 어떻게 설정하는 지 잘 모르겠습니다..
설정이 안되는 것 같아서 hoxy... 알려주실 분?

- Header 컴포넌트 추가하면 에러떠서 일단 주석처리했습니다-!

늦어서 죄송합니다 ㅠ! 피드백 마구마구 부탁드려요 🥲❤️

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/f36de638-95bd-4c9a-8c68-514851b93efb)

## 🔗 Reference

2024-11-25 11:31 UTC, m2na7 requested changes

2024-11-25 11:31 UTC, m2na7 commented on src/pages/HotelDetailPage/Components/HotelDetail/Detail.style.ts
> +  font-size: 14px;
해당 부분 font-size를 theme으로 설정해주세요 !

2024-11-25 11:31 UTC, m2na7 commented on src/pages/HotelDetailPage/Components/HotelDetail/Highlights.style.ts
> +  list-style: none;
`list-style: none` 해당 부분들은 reset.css에 지정되어있으니 다 지워주셔도 무방합니다 !

2024-11-25 11:31 UTC, m2na7 commented on src/pages/HotelDetailPage/Components/HotelDetail/Highlights.tsx
> +        <ul css={RightListStyle(theme)}>
theme을 .tsx파일에서 선언하고 css파일로 넘겨주신 이유가 따로있나요 ?

2024-11-25 11:31 UTC, m2na7 commented on src/pages/HotelDetailPage/Components/HotelDetail/Location.style.ts
> +  position: relative;
`position: relative` 해당 부분은 없어도 상관없을 것 같은데 지정해주신 이유가 따로 있나요 ?

2024-11-25 11:31 UTC, m2na7 commented on src/pages/HotelDetailPage/Components/HotelDetail/Location.style.ts
> +  flex-shrink: 0;
px -> rem으로 바꿔주시고, flex-shrink 속성을 사용하 이유가 궁금합니다 !

2024-11-25 11:31 UTC, m2na7 commented on src/pages/HotelDetailPage/Components/HotelDetail/TextReview.tsx
> +          </div>
해당 부분은 따로 컴포넌트로 빼도 괜찮을 것 같은데 어떻게 생각하시나요 ?

2024-11-25 11:31 UTC, m2na7 commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +      <Location />
`<Vector48 />` 해당 부분은 각 컴포넌트의 마지막 줄에 선언해주거나, 
아예 사용하지 않고 border-bottom을 통해 수정할 수 있을 것 같아요.
컴포넌트를 선언해주고자 한다면 네이밍(Vector48)을 적절하게 변경해주면 좋을 것 같아요 !

2024-11-25 13:29 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/Components/HotelDetail/Detail.style.ts
> +  font-size: 14px;
수정했습니다!

2024-11-25 13:39 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/Components/HotelDetail/Location.style.ts
> +  flex-shrink: 0;
엇 피그마 살펴보니 flex-shrink 가 있길래..?
😂😂 삭제해도 무방하니 삭제처리 했습니다 ㅎㅎ..
+ rem 으로 변경했어요 -!

2024-11-25 13:58 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/Components/HotelDetail/Highlights.tsx
> +        <ul css={RightListStyle(theme)}>
이거 처음에는 라이트/다크모드 구현 연습하다가 손에 익어서 이렇게 썼었는데 엊그제 솝커톤에서도 화랑님이 같은 부분 지적해 주셨어요 😂 동적 구현 아니면 삭제해도 무방하다고... 헣ㅎ
짚어주셔서 감사해요-! 삭제했습니다!

2024-11-25 15:00 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/Components/HotelDetail/TextReview.tsx
> +          </div>
컴포넌트로 빼는 방법도 고려를 해봤는데 그렇게 많지도 않고 3개 밖에 없어서요 😂 다 쓰고 확인해봤는데 그렇게 길지도 않고 저 한 곳에서만 쓰이니까 그냥 사용해도 괜찮을 것 같은데... 컴포넌트로 뺄까욥?

2024-11-25 15:31 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +      <Location />
아하아하 각 컴포넌트의 마지막 줄에 선언하는 방법도 있겠네요! 해당 부분 수정하겠습니다!

2024-11-25 15:44 UTC, m2na7 commented on src/pages/HotelDetailPage/Components/HotelDetail/TextReview.tsx
> +          </div>
정답은 없으니까 그대로 냅둬도 될 것 같아요. 의견 감사합니다 ~

2024-11-25 15:46 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/Components/HotelDetail/Location.style.ts
> +  position: relative;
처음에 이미지말고 svg 파일 두 개를 겹쳐서 하려다가 이미지로 바꿨는데 그때 아마 붙여넣다가 들어간 것 같아오 😂🥲... 수정했습니다!

2024-11-25 15:47 UTC, m2na7 commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +      <Location />
`~Page.tsx` 파일은 한 눈에 어떤 컴포넌트들이 조립되어있는지 보이는게 중요하다고 생각해서, 가독성을 위해 분리해주는게 좋다고 생각했습니다 ~

2024-11-26 15:14 UTC, m2na7 commented on src/assets/svg/Ellipse27.tsx
> +import * as React from "react";
`import * as React from "react";` 해당 부부은 전부 지워주세요!
자동으로 생성되는데, 빌드시에 오류가 생깁니다 !

2024-11-27 04:20 UTC, hansoojeongsj commented on src/pages/HotelDetailPage/Components/HotelDetail/Highlights.tsx
> +        <ul css={RightListStyle(theme)}>
오 저는 이걸 처음 봐서 이렇게도 배워갑니다 ! 솝커톤 때 서로 코드를 봐줬다니,, 역시 대상팀 👍👍

2024-11-27 05:32 UTC, hansoojeongsj reviewed
다음엔 브랜치 소문자로 파주시면 좋을 것 같아요!
저도 png로 넣으니까 이미지가 많이 깨지더라구요.. 지도 svg로 넣어주시면 예쁠 것 같아요
진짜진짜 손 많이 가는 부분이었을 것 같은데 최고 !!👍👍

2024-11-27 05:32 UTC, hansoojeongsj commented on public/svg/베스트셀러.svg
요건 파일명이 원래 이런가요..?!

2024-11-27 05:32 UTC, hansoojeongsj commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +import { BrowserRouter as Router } from "react-router-dom";
저는 실행 했을 때, router가 중복이라 오류가 나는데 혹시.. 괜찮으신가요?!

2024-11-27 05:32 UTC, hansoojeongsj commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +      <HotelCarousel />
번외 이야기이긴 한데, 피그마로는 border-radius가 없어야 하는데 carousel에 border-radius: 10px;으로 적용되어 있어서 qa가지면 언급하실 것 같아요..!

2024-11-27 05:32 UTC, hansoojeongsj commented on src/assets/svg/index.ts
> +export { default as Vector48 } from "./Vector48";
여기도 삭제 부탁드려요!

2024-11-27 05:41 UTC, hansoojeongsj commented on src/pages/HotelDetailPage/Components/HotelDetail/TextReview.style.ts
> +  //여기 글씨가 bold? 설정이 안되는 것 같은데 어떻게 설정해야 할 지 모르겠어요 ;_;
detail2_b_12에서 font-weight가 700이 아니라 500으로 되어 있어서 그런 것 같아요

2024-11-27 05:51 UTC, hansoojeongsj commented on src/pages/HotelDetailPage/Components/HotelDetail/RateReview.style.ts
> +  margin-right: 3.7rem;
1.6rem으로 줘야 할 것 같아요! 글씨랑 circle이랑 겹쳐 보여요..!

2024-11-27 06:00 UTC, hansoojeongsj commented on src/pages/HotelDetailPage/Components/HotelDetail/Location.style.ts
> +    width: 10.6rem;
전체 화면 너비를 375px로 생각해줘야 해서 width를 고정값으로 주기 보다.. NearbyContainer에 width 100%을 주고 NearbyItem에   justify-content: space-between;을 주면 좋을 것 같아요!
```
<li css={NearbyItem} key={index}>
  <span>
      <IcHead2 css={iconStyle(1.2,1.2)}/>
    <span>{place.name}</span>
  </span>
  <span>{place.distance}</span>
</li>
```
하고 space-between잘 될 수 있게 묶어주고.. iconStyle 민하오빠가 만들었는데, 넘 좋더라구요!! 아이콘 스타일 이걸로 줘도 돼요!
하면서 더 좋은 방법 찾으면 알려주세요☺️☺️

2024-11-27 06:03 UTC, Leeyoonji23 commented on public/svg/베스트셀러.svg
아뇽 제가 수정했어요..ㅎ 처음에 영어였는데 딱 보고 특정짓기가 어려워서... 생각해보니 bestseller 도 되는데 왜 한국어로 지었지... 이름 바꿨습니다ㅎㅎ...

2024-11-27 06:04 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +      <HotelCarousel />
앗 맞아요! 이거... 여쭤보고 바꿔야 될 것 같아오 🥲🥲 머지하고 인지했지 뭐예오

2024-11-27 06:09 UTC, Leeyoonji23 commented on src/assets/svg/index.ts
> +export { default as Vector48 } from "./Vector48";
삭제완~

2024-11-27 06:10 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/Components/HotelDetail/TextReview.style.ts
> +  //여기 글씨가 bold? 설정이 안되는 것 같은데 어떻게 설정해야 할 지 모르겠어요 ;_;
뭔가 묘...하게 피그마 글씨체랑 다르지 않나요..? 저만 그렇게 느끼나..? 😂🥲

2024-11-27 06:54 UTC, chaeneey commented on package.json
> +    "@emotion/styled": "^11.13.5",
emotion/styled는 우리 사용하지 않아서 지워줘도 될 것 같아요 !-!

2024-11-27 06:54 UTC, chaeneey commented on src/assets/svg/Ellipse27.tsx
> +import * as React from "react";
해당 부부

2024-11-27 06:54 UTC, chaeneey commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +import { BrowserRouter as Router } from "react-router-dom";
지금 우리 프로젝트에서 
- 📁 `routers` > `pageRoute.tsx` 안에서 path와 그 path에 맞는 컴포넌트를 이미 연결해뒀고, 
- `App.tsx` 파일에서 `createBrowserRouter`를 이용해 라우터 객체 생성 후 `RouterProvider`로 프로젝트에 라우터 설정을 적용한 상태입니다!

=> router는 이미 프로젝트 전체에 세팅을 해둬서, 페이지 컴포넌트 안에서 라우터를 따로 세팅하지 않아도 됩니다! router 관련된 부분은 다 지워주셔도 될 것 같아요! 😊

2024-11-27 06:54 UTC, chaeneey commented on src/pages/HotelDetailPage/Components/HotelDetail/Location.style.ts
> +    width: 10.6rem;
오오 맞아요! 수정님 리뷰처럼 우리 지금 전체 프로젝트를 `375px` 적용하기로 해서 그거에 맞게 전반적으로 수정이 들어가야 할 것 같아요 !-! 🥺

제가 이 부분부터 빠르게 작업해서 전체적으로 페이지가 375로 보이게 수정할테니, 그 전까지는 개발자모드 > 휴대폰 화면으로 보이게 > iphone SE 기준으로 화면 보이게 설정해서 퍼블리싱 해주시면 좋을 것 같아요 !-!

2024-11-27 07:27 UTC, Leeyoonji23 commented on src/assets/svg/Ellipse27.tsx
> +import * as React from "react";
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-11-27 07:27 UTC, Leeyoonji23 commented on src/pages/HotelDetailPage/HotelDetailPage.tsx
> +import { BrowserRouter as Router } from "react-router-dom";
삭제 완료~~

2024-11-28 06:09 UTC, m2na7 approved these changes

2024-11-28 07:40 UTC, closed without merging